### ISSUE TITLE
process launch failed: Disabled

### ISSUE THREAD

**Issue by izouxv** [Naituw/IPAPatch#11]
error: failed to launch '/private/var/containers/Bundle/Application/C43DE802-DB41-490A-948F-2142CA6CA826/IPAPatch-DummyApp.app' -- process launch failed: Disabled

**Comment by Naituw** [comment]
Did you set the `Background Fetch` debug options?
check this: http://stackoverflow.com/questions/26977658/could-not-launch-app-process-launch-failed-disabled

**Comment by Naituw** [comment]
@izouxv Any updates? I'm interested in how you solve this. :)
