### ISSUE TITLE
想请教下该项目下如何用aspect啊

### ISSUE THREAD

**Issue by lizhaobomb** [Naituw/IPAPatch#13]
我新建的UIViewController的分类都会报错啊[UIViewController aspect_hookSelector:withOptions:usingBlock:error:]: unrecognized selector sent to class 0x1affacf50

**Comment by Naituw** [comment]
Would you post your code in the comment?

**Comment by lizhaobomb** [comment]
我就什么都没写，就是写了个分类
@implementation UIViewController (Logging)

+ (void)load {
    [UIViewController aspect_hookSelector:@selector(viewWillAppear:)
                              withOptions:AspectPositionAfter
                               usingBlock:^(id<AspectInfo> aspectInfo){
                                   NSLog(@"Current VC is %@", [aspectInfo instance]);
                               } error:NULL];
}
可能是我代码的位置放错了吧。。我放到IPAPatch目录下了，结果就直接crash了。。不过我放到DummyApp目录下的话，不crash了，不过代码好像不执行啊，我还没搞懂这个要怎么才能执行。。

**Comment by wang9262** [comment]
Faced the same problem.And solved by @Naituw 's  method metioned above.

What a great work!!! Thanks!

**Comment by Naituw** [comment]
@lizhaobomb I will close this issue now, if it's not your case, please comment below.

**Comment by lizhaobomb** [comment]
太棒了，我的也解决了。谢谢 @Naituw
