### ISSUE TITLE
有一个比较好的建议

### ISSUE THREAD

**Issue by phpmaple** [Naituw/IPAPatch#14]
可否类似reveal加载动态库的方法  集成一个 Cycript
然后设置端口号  在真机运行之后可以 ./cycipt -r 192.168.1.101:8888
就可以在命令行用 cycipt 了

**Comment by Naituw** [comment]
Great idea, I will take a look later. You can try it yourself also :)

**Comment by JeziL** [comment]
Tried that and the app crashed at the port binding function: `void CYListenServer(short port)`:

```
libc++abi.dylib: terminating with uncaught exception of type CYPoolError
```

Anyone succeeded?

**Comment by Naituw** [comment]
@JeziL same error here, still trying to find out message of the exception

**Comment by Naituw** [comment]
Hey guys, I think `CYPoolError` is only present on new version of `Cycript`, and throws when I link it directly to a empty project too, no matter device or simulators.

I tried an older version of `Cycript.framework`, which successfully integrated with Youtube. I uploaded it as a new demo at here: https://github.com/Naituw/IPAPatch/releases/tag/1.0.1

**Comment by gonnaMad** [comment]
3Q for solving my problem
