### ISSUE TITLE
Crashed after add Aspects

### ISSUE THREAD

**Issue by nonstriater** [Naituw/IPAPatch#18]
I'm get a crash After I add Aspects like :

```
dyld: Symbol not found: ___NSArray0__
  Referenced from: /private/var/mobile/Containers/Bundle/Application/8AA1CE34-3079-4827-BA18-27AA13F7AB0B/IPAPatch-DummyApp.app/Dylibs/IPAPatch (which was built for iOS 10.3)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /private/var/mobile/Containers/Bundle/Application/8AA1CE34-3079-4827-BA18-27AA13F7AB0B/IPAPatch-DummyApp.app/Dylibs/IPAPatch
```

Aspects added under `IAPPatch` target, It work fine when I remove Aspects framework.  anyone  else happened  on this?

**Comment by Naituw** [comment]
@nonstriater Would you try to set the deployment target of IPAPatch to a lower version (lower than your device)?

**Comment by nonstriater** [comment]
It works, thanks  @Naituw . can you tell me why ?

**Comment by Naituw** [comment]
The iOS SDK link with your binary **dynamically**, which means function that SDK provide, changes between iOS versions, but not your binary/Xcode versions.
 
If the `Deployment Target` is too high. Your binary may include some new stuff(symbols) only available in newer iOS systems (`___NSArray0___` in this case), cause your binary fail to load at runtime.

I have also set `IPAPatch`'s default deployment target to ios8.0 with this commit 1b59e6e01904c0acf10850c796d691dcfdc0c5f8

**Comment by nonstriater** [comment]
thanks for the answer! @Naituw
