### ISSUE TITLE
Can not launch after the installation is complete

### ISSUE THREAD

**Issue by bennyzqliu** [Naituw/IPAPatch#19]
after app installed, xcode show the tip "process launch failed: Disabled"
![image](https://cloud.githubusercontent.com/assets/7959910/24387836/087aa43c-13aa-11e7-9e1f-f535be91aae7.png)

**Comment by Naituw** [comment]
Would you provide the ipa and device model you use?

**Comment by bennyzqliu** [comment]
looks like a problem with ipa.
when i use the ipa exported from iTunes, will cause the problem.
if i use ourself ipa, it works well

**Comment by Naituw** [comment]
The ipa use with IPAPatch should be decrypted, if you export ipa directly from iTunes, they are not decrypted. You can get decrypted ipa from jailbroken device or ipa download site such as https://iphonecake.com
