### ISSUE TITLE
Project path with white-spaces not working.

### ISSUE THREAD

**Issue by unixzii** [Naituw/IPAPatch#2]
It seems that the script won't handle paths with white-spaces, any path with white-spaces will be split to two commands and lead to error.

Maybe adding `IFS=$(echo -en "\n\b")` to the start of **patch.sh** can help.

**Comment by Naituw** [comment]
Thanks for your feedback! I fixed this issue with 3f7ff2cda30c7a5385417355e4804a9c622fbefb, and the demo project has been updated as well.
