### ISSUE TITLE
crash !!!

### ISSUE THREAD

**Issue by QKunNO1** [Naituw/IPAPatch#22]
![image](https://cloud.githubusercontent.com/assets/26812259/24541527/722cb384-162a-11e7-8f92-81d901938682.png)
i rename display name add replace ipa . click run bababababba waitting  crash! 100%

**Comment by QKunNO1** [comment]
my ipa dowload from pp助手 
![image](https://cloud.githubusercontent.com/assets/26812259/24541742/4aa4931c-162b-11e7-8715-5c95ec085968.png)

**Comment by LazyDuan** [comment]
the same crash

**Comment by LazyDuan** [comment]
Do you use Reveal in your Project？I find my reason is use it in my project。

**Comment by codwam** [comment]
今日头条我的也是crash了。

**Comment by lionXiao** [comment]
demo crash!!!!

**Comment by chenjunpu** [comment]
me too！！ my app download from iphonecake
<img width="973" alt="2017-06-02 10 36 34" src="https://cloud.githubusercontent.com/assets/14036062/26708631/89911f5c-477f-11e7-93dd-4a4cf0c65f03.png">

**Comment by Naituw** [comment]
Would you setup a repository that can reproduce this issue?

**Comment by Naituw** [comment]
Closing since no reply
