### ISSUE TITLE
Embedding .bundle into target app

### ISSUE THREAD

**Issue by anivaros** [Naituw/IPAPatch#25]
Hello! Is it possible to embed .bundle, that coming with framework into app? Or another resources.

**Comment by Naituw** [comment]
Currently IPAPatch only injects dynamic binaries, I will add this feature at future, pull requests are also welcome too :P

**Comment by Naituw** [comment]
This is now supported, by 66a80b7c0550a3e7d73d91db4204ad2b3d82e248
