### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by d6638219** [Naituw/IPAPatch#26]
dyld: Library not loaded: @executable_path/Dylibs/IPAPatch
  Referenced from: /var/containers/Bundle/Application/DFA4D68A-13FB-4460-B5EE-3625ED932EFF/IPAPatch-DummyApp.app/Autohome
  Reason: no suitable image found.  Did find:
	/var/containers/Bundle/Application/DFA4D68A-13FB-4460-B5EE-3625ED932EFF/IPAPatch-DummyApp.app/Dylibs/IPAPatch: mach-o, but wrong architecture
	/private/var/containers/Bundle/Application/DFA4D68A-13FB-4460-B5EE-3625ED932EFF/IPAPatch-DummyApp.app/Dylibs/IPAPatch: mach-o, but wrong architecture

**Comment by Naituw** [comment]
I think this is due to the build architecture for IPAPatch is not match the binary you use
