### ISSUE TITLE
Code Injection and create IPA

### ISSUE THREAD

**Issue by twitteriosdevelopment** [Naituw/IPAPatch#31]
Hey, this might be off topic but how does the file IPA PATCH ENTRY block a method being called from the app itself? Also how would I make an IPA from here?

**Comment by Naituw** [comment]
> how does the file IPA PATCH ENTRY block a method being called from the app itself?

This can be done by using runtime techniques like method swizzling

> how would I make an IPA from here

I've added ipa file creation feature with b5b4387489c6a0a8c84c63ee1bdfbdd91035f072
