### ISSUE TITLE
Show black screen when running in latest version

### ISSUE THREAD

**Issue by wonderffee** [Naituw/IPAPatch#34]
and touch the iPhone screen, below log is printed:
2017-09-01 18:46:36.642 11[9777:1868054] unexpected nil window in _UIApplicationHandleEventFromQueueEvent, _windowServerHitTestWindow: <UIClassicWindow: 0x126628440; frame = (0 0; 375 667); userInteractionEnabled = NO; gestureRecognizers = <NSArray: 0x126549db0>; layer = <UIWindowLayer: 0x126623be0>>

But if I download the youtube demo and run it, all is well! And replace youtube ipa file with my target ipa file, it also runs well!

Just don't know why.

The latest version also has a problem: One alert view with content of "Could not inspect the application package" is presented by Xcode after installing app to device successfully. My solution is changing product name to simple "11” in "IPAPatch-DummyApp" target.

Xcode version: Version 8.3.3
iPhone6, iOS 9.2

**Comment by wonderffee** [comment]
Just do addition test, commit 4c15e99 is right, commit b5b4387 show black screen.
Maybe the problem is in commit b5b4387.

**Comment by wonderffee** [comment]
Very weird, this problem doesn't exist in another Mac.....

**Comment by Geforceyu** [comment]
I have the same problem,did you solved?

**Comment by wonderffee** [comment]
No, then I use MonkeyDev
