### ISSUE TITLE
使用自己砸壳的ipa文件安装成功后只显示启动界面

### ISSUE THREAD

**Issue by wonderffee** [Naituw/IPAPatch#36]
1. 在越狱的iTouch5 iOS7.0.2环境下使用dumpcrypted进行的砸壳
2. 所使用的ipa 二进制文件armv7 decrypted, arm64 crypted，运行IPAPatch安装成功后会一直显示启动画面，提示下面的日志：
[Mach] exception: 0x%x, count: %d, code: 0x%llx 0x%llx
[Mach] Forwarding exception: 0x%x, port: %d behavior: %d, flavor: %d)
3. 不能使用thin ipa，因为会提示have no permission或者提示必须用fat file
4. 同样的ipa通过iFunBox可以成功安装至越狱设备中，类似的工具MonkeyDev完全可以正常使用此ipa文件。

环境：
MacOS 10.12.5
Xcode 8.3.3
iPhone5c 10.3.3

**Comment by Naituw** [comment]
I think this is one issue? would you please setup a demo repo, so I can fix it? Thanks!

**Comment by YangSugar** [comment]
> 1. 在越狱的iTouch5 iOS7.0.2环境下使用dumpcrypted进行的砸壳
> 2. 所使用的ipa 二进制文件armv7 decrypted, arm64 crypted，运行IPAPatch安装成功后会一直显示启动画面，提示下面的日志：
>    [Mach] exception: 0x%x, count: %d, code: 0x%llx 0x%llx
>    [Mach] Forwarding exception: 0x%x, port: %d behavior: %d, flavor: %d)
> 3. 不能使用thin ipa，因为会提示have no permission或者提示必须用fat file
> 4. 同样的ipa通过iFunBox可以成功安装至越狱设备中，类似的工具MonkeyDev完全可以正常使用此ipa文件。
> 
> 环境：
> MacOS 10.12.5
> Xcode 8.3.3
> iPhone5c 10.3.3
请问解决了吗
