### ISSUE TITLE
无法archive出正确ipa

### ISSUE THREAD

**Issue by kennygui** [Naituw/IPAPatch#38]
目前是否是无法打包为release包吗? 我是企业开发证书,archive之后,打包出来的ipa是ipa_patch那个.只有几十KB,这个是我姿势错了,还是没有做相关支持呢?

**Comment by Naituw** [comment]
Don't archive directly. Instead, use `options.plist`, see `README` for more details

**Comment by kennygui** [comment]
忘了说明,我已经修改了那个key为YES.仍旧看不到ipa , Xcode9 iOS 11

**Comment by Naituw** [comment]
Try build instead of archive
