### ISSUE TITLE
WatchKit app with an invalid bundle identifier

### ISSUE THREAD

**Issue by phpmaple** [Naituw/IPAPatch#4]
When I replace Wechat.ipa to app.ipa, and build, xcode says:

`This app contains a WatchKit app with an invalid bundle identifier. The bundle identifier of a WatchKit app must have a prefix consisting of the companion app's bundle identifier, followed by a '.'.`

**Comment by Naituw** [comment]
This is solved by https://github.com/Naituw/IPAPatch/pull/3

Please comment again if it didn't solve your problem.
