### ISSUE TITLE
couldn’t be opened because you don’t have permission to view it. Even though i have placed my app decrypted with clutch and named it app.ipa

### ISSUE THREAD

**Issue by eclair4151** [Naituw/IPAPatch#49]
in the errors it says:

fatal error: lipo: input file (/Users/tomershemesh/Desktop/IPAPatch-master/Temp/Payload/hq-viewer.app/hq-viewer) must be a fat file when the -thin option is specified
fatal error: lipo: input file (/Users/tomershemesh/Desktop/IPAPatch-master/Temp/Payload/hq-viewer.app/hq-viewer) must be a fat file when the -thin option is specified
Error: Input file doesn't exist!
Error: Input file doesn't exist!
fatal error: lipo: can't open input file: /Users/tomershemesh/Desktop/IPAPatch-master/Temp/hq-viewer_armv7_with_symbol (No such file or directory)
cp: /Users/tomershemesh/Desktop/IPAPatch-master/Temp/hq-viewer_with_symbol: No such file or directory
TARGET_APP_PATH: /Users/tomershemesh/Library/Developer/Xcode/DerivedData/IPAPatch-cvroycbarnteuxerldacbblocvzi/Build/Products/Debug-iphoneos/IPAPatch-DummyApp.app
     Install Load: IPAPatchFramework -> @executable_path/Dylibs/IPAPatchFramework
chmod: /Users/tomershemesh/Library/Developer/Xcode/DerivedData/IPAPatch-cvroycbarnteuxerldacbblocvzi/Build/Products/Debug-iphoneos/IPAPatch-DummyApp.app/hq-viewer: No such file or directory

I think the app is fine though because i can install it just fine with cydia impactor

**Comment by KAMIKAZEUA** [comment]
@Naituw I've notice that this problem persist if ipa was like build with bytecode.

In the App Store it will looks like:

![screen shot 1](https://user-images.githubusercontent.com/3391456/36760932-724a5414-1c25-11e8-8988-c33cedab9db2.png)

But for apps like that(without bytecode): 

![screen shot 2](https://user-images.githubusercontent.com/3391456/36760961-8e0ac918-1c25-11e8-8837-ea5f77085adc.png)

It will work fine.

**Comment by eclair4151** [comment]
yes i found have found a way around this. How you do it is make sure when you crack the app, make sure you install it from iTunes, NOT the appstore on the phone. like go onto itunes app on your computer, go to the apps section download the app from there, and then plug your phone in and from itunes sync the app to your phone. This forces the app to not be sliced and have missing assets for certain devices.

**Comment by KAMIKAZEUA** [comment]
I took .ipa of simple app found via google search as example to learn how this works.
My phone without jailbreak, so I can't do that and I can't install jailbreak because I'm using latest version of iOS.

**Comment by yuzhouheike** [comment]
The file “IPAPatch-DummyApp” couldn’t be opened because you don’t have permission to view it.

**Comment by youshaoduo** [comment]
@mcfans 
it works for me, thank you!

**Comment by yuzhouheike** [comment]
@mcfans thank you!

**Comment by Naituw** [comment]
> I founded a workaround for this.Set `RESTORE_SYMBOLS` in `Tools/options.plist` to `NO`. This works for me.

Thanks, I just disabled this option by default with https://github.com/Naituw/IPAPatch/commit/f87fca2ea732177b670f0380414efc201e981fd8
