### ISSUE TITLE
我运行了demo到真机上面但是reveal并没有显示

### ISSUE THREAD

**Issue by phpmaple** [Naituw/IPAPatch#5]
真机上已经显示被 Hacked reveal中不显示

**Comment by phpmaple** [comment]
发现问题了，也是因为项目文件夹有空格的原因

**Comment by Naituw** [comment]
Thanks for your feedback! I fixed this issue with 3f7ff2cda30c7a5385417355e4804a9c622fbefb, and the demo project has been updated as well.
