### ISSUE TITLE
error: memory read failed for 0x0

### ISSUE THREAD

**Issue by petervdtoorn** [Naituw/IPAPatch#50]
When i try to run the facebook ipa (different versions). Everything works fine, except when i try to open a company (example restaurant) page in facebook. Then i get the error:

error: memory read failed for 0x0, Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

This is without any custom code injection. I also tried different phones and different IOs versions.

**Comment by Naituw** [comment]
The ipa file may not decrypted correctly,See:
- https://forum.iphonecake.com/index.php?/topic/324827-facebook-1380-by-ghay-free-app/?p=420262
- https://www.jianshu.com/p/1c6c36b1ae58 (Chinese)
