### ISSUE TITLE
It doesn't work in Facebook app.

### ISSUE THREAD

**Issue by ywqqqqq** [Naituw/IPAPatch#53]
Hi, 
I am going to figure out the structure of Facebook with reveal, but unfortunately I don't have a jailbreak device. 
Twitter and Youtube work fine. When it come to Facebook, it's not working. All decrypted ipa downloaded from phonecake. I have tried different version of Facebook that I got from phonecake. None of them could run normally. 

I need some help, thx.

**Comment by Naituw** [comment]
If the app crashes when you login, you may get an ipa improperly decrypted, compare your ipa with store/undecrypted version, are the contents of `Payload/Facebook.app/Frameworks` the same?
