### ISSUE TITLE
Using Swift

### ISSUE THREAD

**Issue by XMB5** [Naituw/IPAPatch#54]
Hello,
I want to use Swift instead of Objective-C. I have tried enabling the objective-c interface header, but when using `#import "IPAPatch_DummyApp-Swift.h` the header is not found. I enabled `DEFINES MODULE`, but the error still occurred. Do you know how to make this work?
Thanks

**Comment by StarBlayze** [comment]
man I'm wondering this too, I only learned Swift, (it's a lot easier) I hope it's possible.

**Comment by XMB5** [comment]
I got swift working! I played with lots of settings, so I am not sure which one caused it to work. Here is the project: [IPAPatch](https://www.dropbox.com/s/0715siy2ze8uwha/ExpressVPNPatch.zip?dl=0).

**Comment by XMB5** [comment]
You can use [my fork](https://github.com/XMB5/IPAPatch-Swift) which supports swift
