### ISSUE TITLE
You don’t have permission.

### ISSUE THREAD

**Issue by VictDog** [Naituw/IPAPatch#56]
The file “IPAPatch-DummyApp.app” couldn’t be opened because you don’t have permission to view it. 
总是出现这个问题，按照网上的说法，修改plist 也不行

**Comment by mengzhihoing** [comment]
@VictDog first of all. repplace the app.ipa

**Comment by sszzwzb** [comment]
不太明白

**Comment by ddviper** [comment]
Follow “Project->options.plist->RESTORE_SYMBOLS->>NO”, and OK!

**Comment by Naituw** [comment]
> Follow “Project->options.plist->RESTORE_SYMBOLS->>NO”, and OK!

Thanks, I just disabled this option by default with https://github.com/Naituw/IPAPatch/commit/f87fca2ea732177b670f0380414efc201e981fd8
