### ISSUE TITLE
Product folder not appearing.

### ISSUE THREAD

**Issue by Kozmick** [Naituw/IPAPatch#57]
After building the project no finished .ipa can be found. Also I did enable ipa generation.

**Comment by rhettrhett1** [comment]
Same. Find a fix?

**Comment by Kozmick** [comment]
I haven't yet sadly.

**Comment by BillWSY** [comment]
Try adding 
```
"${SRCROOT}/Tools/create_ipa.sh"
```
to `Run Script` under `Build Phases`, right below `"${SRCROOT}/Tools/patch.sh"`
