### ISSUE TITLE
The file “IPAPatch-DummyApp” couldn’t be opened because you don’t have permission to view it.

### ISSUE THREAD

**Issue by LiuSky** [Naituw/IPAPatch#6]
The file “IPAPatch-DummyApp” couldn’t be opened because you don’t have permission to view it.

**Comment by Naituw** [comment]
Duplicate with https://github.com/Naituw/IPAPatch/issues/1

> Seems you didn't replace Assets/app.ipa with decrypted ipa you downloaded, see step 2 of instructions in README.md.
