### ISSUE TITLE
Can't patch Facebook IPA

### ISSUE THREAD

**Issue by nghminh163** [Naituw/IPAPatch#62]
When i patch Facebook.ipa i have some error:"Facebook[246:10484] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]'"
Hmmm, Can you help me?

**Comment by Naituw** [comment]
see https://github.com/Naituw/IPAPatch/issues/53
