### ISSUE TITLE
FridaGadget.dylib + FridaGadget.config - how?

### ISSUE THREAD

**Issue by evandrix** [Naituw/IPAPatch#63]
@ https://www.frida.re/docs/gadget
FridaGadget.dylib => /IPAPatch/Assets/Dylibs/FridaGadget.dylib
FridaGadget.config => ?

**Comment by evandrix** [comment]
![screenshot](https://user-images.githubusercontent.com/169669/55658713-3bb6fa80-5831-11e9-80ab-61357d32796d.png)

can't get it to listen on 0.0.0.0

**Comment by Naituw** [comment]
try the `IPAPatch/Assets/Resources` folder
